// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timeline.proto

#ifndef PROTOBUF_timeline_2eproto__INCLUDED
#define PROTOBUF_timeline_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_timeline_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsuserImpl();
void InitDefaultsuser();
void InitDefaultspostImpl();
void InitDefaultspost();
void InitDefaultsfollow_requestImpl();
void InitDefaultsfollow_request();
void InitDefaultsfollow_responseImpl();
void InitDefaultsfollow_response();
void InitDefaultsunfollow_requestImpl();
void InitDefaultsunfollow_request();
void InitDefaultsunfollow_responseImpl();
void InitDefaultsunfollow_response();
void InitDefaultslist_requestImpl();
void InitDefaultslist_request();
void InitDefaultslist_responseImpl();
void InitDefaultslist_response();
inline void InitDefaults() {
  InitDefaultsuser();
  InitDefaultspost();
  InitDefaultsfollow_request();
  InitDefaultsfollow_response();
  InitDefaultsunfollow_request();
  InitDefaultsunfollow_response();
  InitDefaultslist_request();
  InitDefaultslist_response();
}
}  // namespace protobuf_timeline_2eproto
namespace timeline {
class follow_request;
class follow_requestDefaultTypeInternal;
extern follow_requestDefaultTypeInternal _follow_request_default_instance_;
class follow_response;
class follow_responseDefaultTypeInternal;
extern follow_responseDefaultTypeInternal _follow_response_default_instance_;
class list_request;
class list_requestDefaultTypeInternal;
extern list_requestDefaultTypeInternal _list_request_default_instance_;
class list_response;
class list_responseDefaultTypeInternal;
extern list_responseDefaultTypeInternal _list_response_default_instance_;
class post;
class postDefaultTypeInternal;
extern postDefaultTypeInternal _post_default_instance_;
class unfollow_request;
class unfollow_requestDefaultTypeInternal;
extern unfollow_requestDefaultTypeInternal _unfollow_request_default_instance_;
class unfollow_response;
class unfollow_responseDefaultTypeInternal;
extern unfollow_responseDefaultTypeInternal _unfollow_response_default_instance_;
class user;
class userDefaultTypeInternal;
extern userDefaultTypeInternal _user_default_instance_;
}  // namespace timeline
namespace timeline {

// ===================================================================

class user : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.user) */ {
 public:
  user();
  virtual ~user();

  user(const user& from);

  inline user& operator=(const user& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  user(user&& from) noexcept
    : user() {
    *this = ::std::move(from);
  }

  inline user& operator=(user&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const user& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const user* internal_default_instance() {
    return reinterpret_cast<const user*>(
               &_user_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(user* other);
  friend void swap(user& a, user& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline user* New() const PROTOBUF_FINAL { return New(NULL); }

  user* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const user& from);
  void MergeFrom(const user& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(user* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user = 1;
  void clear_user();
  static const int kUserFieldNumber = 1;
  const ::std::string& user() const;
  void set_user(const ::std::string& value);
  #if LANG_CXX11
  void set_user(::std::string&& value);
  #endif
  void set_user(const char* value);
  void set_user(const char* value, size_t size);
  ::std::string* mutable_user();
  ::std::string* release_user();
  void set_allocated_user(::std::string* user);

  // @@protoc_insertion_point(class_scope:timeline.user)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultsuserImpl();
};
// -------------------------------------------------------------------

class post : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.post) */ {
 public:
  post();
  virtual ~post();

  post(const post& from);

  inline post& operator=(const post& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  post(post&& from) noexcept
    : post() {
    *this = ::std::move(from);
  }

  inline post& operator=(post&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const post& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const post* internal_default_instance() {
    return reinterpret_cast<const post*>(
               &_post_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(post* other);
  friend void swap(post& a, post& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline post* New() const PROTOBUF_FINAL { return New(NULL); }

  post* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const post& from);
  void MergeFrom(const post& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(post* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string content = 1;
  void clear_content();
  static const int kContentFieldNumber = 1;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // string owner = 2;
  void clear_owner();
  static const int kOwnerFieldNumber = 2;
  const ::std::string& owner() const;
  void set_owner(const ::std::string& value);
  #if LANG_CXX11
  void set_owner(::std::string&& value);
  #endif
  void set_owner(const char* value);
  void set_owner(const char* value, size_t size);
  ::std::string* mutable_owner();
  ::std::string* release_owner();
  void set_allocated_owner(::std::string* owner);

  // @@protoc_insertion_point(class_scope:timeline.post)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  ::google::protobuf::internal::ArenaStringPtr owner_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultspostImpl();
};
// -------------------------------------------------------------------

class follow_request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.follow_request) */ {
 public:
  follow_request();
  virtual ~follow_request();

  follow_request(const follow_request& from);

  inline follow_request& operator=(const follow_request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  follow_request(follow_request&& from) noexcept
    : follow_request() {
    *this = ::std::move(from);
  }

  inline follow_request& operator=(follow_request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const follow_request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const follow_request* internal_default_instance() {
    return reinterpret_cast<const follow_request*>(
               &_follow_request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(follow_request* other);
  friend void swap(follow_request& a, follow_request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline follow_request* New() const PROTOBUF_FINAL { return New(NULL); }

  follow_request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const follow_request& from);
  void MergeFrom(const follow_request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(follow_request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .timeline.user user1 = 1;
  bool has_user1() const;
  void clear_user1();
  static const int kUser1FieldNumber = 1;
  const ::timeline::user& user1() const;
  ::timeline::user* release_user1();
  ::timeline::user* mutable_user1();
  void set_allocated_user1(::timeline::user* user1);

  // .timeline.user user2 = 2;
  bool has_user2() const;
  void clear_user2();
  static const int kUser2FieldNumber = 2;
  const ::timeline::user& user2() const;
  ::timeline::user* release_user2();
  ::timeline::user* mutable_user2();
  void set_allocated_user2(::timeline::user* user2);

  // @@protoc_insertion_point(class_scope:timeline.follow_request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::timeline::user* user1_;
  ::timeline::user* user2_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultsfollow_requestImpl();
};
// -------------------------------------------------------------------

class follow_response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.follow_response) */ {
 public:
  follow_response();
  virtual ~follow_response();

  follow_response(const follow_response& from);

  inline follow_response& operator=(const follow_response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  follow_response(follow_response&& from) noexcept
    : follow_response() {
    *this = ::std::move(from);
  }

  inline follow_response& operator=(follow_response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const follow_response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const follow_response* internal_default_instance() {
    return reinterpret_cast<const follow_response*>(
               &_follow_response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(follow_response* other);
  friend void swap(follow_response& a, follow_response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline follow_response* New() const PROTOBUF_FINAL { return New(NULL); }

  follow_response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const follow_response& from);
  void MergeFrom(const follow_response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(follow_response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 success_status = 1;
  void clear_success_status();
  static const int kSuccessStatusFieldNumber = 1;
  ::google::protobuf::int32 success_status() const;
  void set_success_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:timeline.follow_response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 success_status_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultsfollow_responseImpl();
};
// -------------------------------------------------------------------

class unfollow_request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.unfollow_request) */ {
 public:
  unfollow_request();
  virtual ~unfollow_request();

  unfollow_request(const unfollow_request& from);

  inline unfollow_request& operator=(const unfollow_request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  unfollow_request(unfollow_request&& from) noexcept
    : unfollow_request() {
    *this = ::std::move(from);
  }

  inline unfollow_request& operator=(unfollow_request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const unfollow_request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const unfollow_request* internal_default_instance() {
    return reinterpret_cast<const unfollow_request*>(
               &_unfollow_request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(unfollow_request* other);
  friend void swap(unfollow_request& a, unfollow_request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline unfollow_request* New() const PROTOBUF_FINAL { return New(NULL); }

  unfollow_request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const unfollow_request& from);
  void MergeFrom(const unfollow_request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(unfollow_request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .timeline.user user1 = 1;
  bool has_user1() const;
  void clear_user1();
  static const int kUser1FieldNumber = 1;
  const ::timeline::user& user1() const;
  ::timeline::user* release_user1();
  ::timeline::user* mutable_user1();
  void set_allocated_user1(::timeline::user* user1);

  // .timeline.user user2 = 2;
  bool has_user2() const;
  void clear_user2();
  static const int kUser2FieldNumber = 2;
  const ::timeline::user& user2() const;
  ::timeline::user* release_user2();
  ::timeline::user* mutable_user2();
  void set_allocated_user2(::timeline::user* user2);

  // @@protoc_insertion_point(class_scope:timeline.unfollow_request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::timeline::user* user1_;
  ::timeline::user* user2_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultsunfollow_requestImpl();
};
// -------------------------------------------------------------------

class unfollow_response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.unfollow_response) */ {
 public:
  unfollow_response();
  virtual ~unfollow_response();

  unfollow_response(const unfollow_response& from);

  inline unfollow_response& operator=(const unfollow_response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  unfollow_response(unfollow_response&& from) noexcept
    : unfollow_response() {
    *this = ::std::move(from);
  }

  inline unfollow_response& operator=(unfollow_response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const unfollow_response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const unfollow_response* internal_default_instance() {
    return reinterpret_cast<const unfollow_response*>(
               &_unfollow_response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(unfollow_response* other);
  friend void swap(unfollow_response& a, unfollow_response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline unfollow_response* New() const PROTOBUF_FINAL { return New(NULL); }

  unfollow_response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const unfollow_response& from);
  void MergeFrom(const unfollow_response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(unfollow_response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 success_status = 1;
  void clear_success_status();
  static const int kSuccessStatusFieldNumber = 1;
  ::google::protobuf::int32 success_status() const;
  void set_success_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:timeline.unfollow_response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 success_status_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultsunfollow_responseImpl();
};
// -------------------------------------------------------------------

class list_request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.list_request) */ {
 public:
  list_request();
  virtual ~list_request();

  list_request(const list_request& from);

  inline list_request& operator=(const list_request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  list_request(list_request&& from) noexcept
    : list_request() {
    *this = ::std::move(from);
  }

  inline list_request& operator=(list_request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const list_request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const list_request* internal_default_instance() {
    return reinterpret_cast<const list_request*>(
               &_list_request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(list_request* other);
  friend void swap(list_request& a, list_request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline list_request* New() const PROTOBUF_FINAL { return New(NULL); }

  list_request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const list_request& from);
  void MergeFrom(const list_request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(list_request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .timeline.user user1 = 1;
  bool has_user1() const;
  void clear_user1();
  static const int kUser1FieldNumber = 1;
  const ::timeline::user& user1() const;
  ::timeline::user* release_user1();
  ::timeline::user* mutable_user1();
  void set_allocated_user1(::timeline::user* user1);

  // @@protoc_insertion_point(class_scope:timeline.list_request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::timeline::user* user1_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultslist_requestImpl();
};
// -------------------------------------------------------------------

class list_response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:timeline.list_response) */ {
 public:
  list_response();
  virtual ~list_response();

  list_response(const list_response& from);

  inline list_response& operator=(const list_response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  list_response(list_response&& from) noexcept
    : list_response() {
    *this = ::std::move(from);
  }

  inline list_response& operator=(list_response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const list_response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const list_response* internal_default_instance() {
    return reinterpret_cast<const list_response*>(
               &_list_response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(list_response* other);
  friend void swap(list_response& a, list_response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline list_response* New() const PROTOBUF_FINAL { return New(NULL); }

  list_response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const list_response& from);
  void MergeFrom(const list_response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(list_response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string followers = 1;
  void clear_followers();
  static const int kFollowersFieldNumber = 1;
  const ::std::string& followers() const;
  void set_followers(const ::std::string& value);
  #if LANG_CXX11
  void set_followers(::std::string&& value);
  #endif
  void set_followers(const char* value);
  void set_followers(const char* value, size_t size);
  ::std::string* mutable_followers();
  ::std::string* release_followers();
  void set_allocated_followers(::std::string* followers);

  // string active_users = 2;
  void clear_active_users();
  static const int kActiveUsersFieldNumber = 2;
  const ::std::string& active_users() const;
  void set_active_users(const ::std::string& value);
  #if LANG_CXX11
  void set_active_users(::std::string&& value);
  #endif
  void set_active_users(const char* value);
  void set_active_users(const char* value, size_t size);
  ::std::string* mutable_active_users();
  ::std::string* release_active_users();
  void set_allocated_active_users(::std::string* active_users);

  // @@protoc_insertion_point(class_scope:timeline.list_response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr followers_;
  ::google::protobuf::internal::ArenaStringPtr active_users_;
  mutable int _cached_size_;
  friend struct ::protobuf_timeline_2eproto::TableStruct;
  friend void ::protobuf_timeline_2eproto::InitDefaultslist_responseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// user

// string user = 1;
inline void user::clear_user() {
  user_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& user::user() const {
  // @@protoc_insertion_point(field_get:timeline.user.user)
  return user_.GetNoArena();
}
inline void user::set_user(const ::std::string& value) {
  
  user_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:timeline.user.user)
}
#if LANG_CXX11
inline void user::set_user(::std::string&& value) {
  
  user_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:timeline.user.user)
}
#endif
inline void user::set_user(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:timeline.user.user)
}
inline void user::set_user(const char* value, size_t size) {
  
  user_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:timeline.user.user)
}
inline ::std::string* user::mutable_user() {
  
  // @@protoc_insertion_point(field_mutable:timeline.user.user)
  return user_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* user::release_user() {
  // @@protoc_insertion_point(field_release:timeline.user.user)
  
  return user_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void user::set_allocated_user(::std::string* user) {
  if (user != NULL) {
    
  } else {
    
  }
  user_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user);
  // @@protoc_insertion_point(field_set_allocated:timeline.user.user)
}

// -------------------------------------------------------------------

// post

// string content = 1;
inline void post::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& post::content() const {
  // @@protoc_insertion_point(field_get:timeline.post.content)
  return content_.GetNoArena();
}
inline void post::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:timeline.post.content)
}
#if LANG_CXX11
inline void post::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:timeline.post.content)
}
#endif
inline void post::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:timeline.post.content)
}
inline void post::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:timeline.post.content)
}
inline ::std::string* post::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:timeline.post.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* post::release_content() {
  // @@protoc_insertion_point(field_release:timeline.post.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void post::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:timeline.post.content)
}

// string owner = 2;
inline void post::clear_owner() {
  owner_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& post::owner() const {
  // @@protoc_insertion_point(field_get:timeline.post.owner)
  return owner_.GetNoArena();
}
inline void post::set_owner(const ::std::string& value) {
  
  owner_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:timeline.post.owner)
}
#if LANG_CXX11
inline void post::set_owner(::std::string&& value) {
  
  owner_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:timeline.post.owner)
}
#endif
inline void post::set_owner(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  owner_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:timeline.post.owner)
}
inline void post::set_owner(const char* value, size_t size) {
  
  owner_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:timeline.post.owner)
}
inline ::std::string* post::mutable_owner() {
  
  // @@protoc_insertion_point(field_mutable:timeline.post.owner)
  return owner_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* post::release_owner() {
  // @@protoc_insertion_point(field_release:timeline.post.owner)
  
  return owner_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void post::set_allocated_owner(::std::string* owner) {
  if (owner != NULL) {
    
  } else {
    
  }
  owner_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), owner);
  // @@protoc_insertion_point(field_set_allocated:timeline.post.owner)
}

// -------------------------------------------------------------------

// follow_request

// .timeline.user user1 = 1;
inline bool follow_request::has_user1() const {
  return this != internal_default_instance() && user1_ != NULL;
}
inline void follow_request::clear_user1() {
  if (GetArenaNoVirtual() == NULL && user1_ != NULL) {
    delete user1_;
  }
  user1_ = NULL;
}
inline const ::timeline::user& follow_request::user1() const {
  const ::timeline::user* p = user1_;
  // @@protoc_insertion_point(field_get:timeline.follow_request.user1)
  return p != NULL ? *p : *reinterpret_cast<const ::timeline::user*>(
      &::timeline::_user_default_instance_);
}
inline ::timeline::user* follow_request::release_user1() {
  // @@protoc_insertion_point(field_release:timeline.follow_request.user1)
  
  ::timeline::user* temp = user1_;
  user1_ = NULL;
  return temp;
}
inline ::timeline::user* follow_request::mutable_user1() {
  
  if (user1_ == NULL) {
    user1_ = new ::timeline::user;
  }
  // @@protoc_insertion_point(field_mutable:timeline.follow_request.user1)
  return user1_;
}
inline void follow_request::set_allocated_user1(::timeline::user* user1) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete user1_;
  }
  if (user1) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      user1 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, user1, submessage_arena);
    }
    
  } else {
    
  }
  user1_ = user1;
  // @@protoc_insertion_point(field_set_allocated:timeline.follow_request.user1)
}

// .timeline.user user2 = 2;
inline bool follow_request::has_user2() const {
  return this != internal_default_instance() && user2_ != NULL;
}
inline void follow_request::clear_user2() {
  if (GetArenaNoVirtual() == NULL && user2_ != NULL) {
    delete user2_;
  }
  user2_ = NULL;
}
inline const ::timeline::user& follow_request::user2() const {
  const ::timeline::user* p = user2_;
  // @@protoc_insertion_point(field_get:timeline.follow_request.user2)
  return p != NULL ? *p : *reinterpret_cast<const ::timeline::user*>(
      &::timeline::_user_default_instance_);
}
inline ::timeline::user* follow_request::release_user2() {
  // @@protoc_insertion_point(field_release:timeline.follow_request.user2)
  
  ::timeline::user* temp = user2_;
  user2_ = NULL;
  return temp;
}
inline ::timeline::user* follow_request::mutable_user2() {
  
  if (user2_ == NULL) {
    user2_ = new ::timeline::user;
  }
  // @@protoc_insertion_point(field_mutable:timeline.follow_request.user2)
  return user2_;
}
inline void follow_request::set_allocated_user2(::timeline::user* user2) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete user2_;
  }
  if (user2) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      user2 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, user2, submessage_arena);
    }
    
  } else {
    
  }
  user2_ = user2;
  // @@protoc_insertion_point(field_set_allocated:timeline.follow_request.user2)
}

// -------------------------------------------------------------------

// follow_response

// int32 success_status = 1;
inline void follow_response::clear_success_status() {
  success_status_ = 0;
}
inline ::google::protobuf::int32 follow_response::success_status() const {
  // @@protoc_insertion_point(field_get:timeline.follow_response.success_status)
  return success_status_;
}
inline void follow_response::set_success_status(::google::protobuf::int32 value) {
  
  success_status_ = value;
  // @@protoc_insertion_point(field_set:timeline.follow_response.success_status)
}

// -------------------------------------------------------------------

// unfollow_request

// .timeline.user user1 = 1;
inline bool unfollow_request::has_user1() const {
  return this != internal_default_instance() && user1_ != NULL;
}
inline void unfollow_request::clear_user1() {
  if (GetArenaNoVirtual() == NULL && user1_ != NULL) {
    delete user1_;
  }
  user1_ = NULL;
}
inline const ::timeline::user& unfollow_request::user1() const {
  const ::timeline::user* p = user1_;
  // @@protoc_insertion_point(field_get:timeline.unfollow_request.user1)
  return p != NULL ? *p : *reinterpret_cast<const ::timeline::user*>(
      &::timeline::_user_default_instance_);
}
inline ::timeline::user* unfollow_request::release_user1() {
  // @@protoc_insertion_point(field_release:timeline.unfollow_request.user1)
  
  ::timeline::user* temp = user1_;
  user1_ = NULL;
  return temp;
}
inline ::timeline::user* unfollow_request::mutable_user1() {
  
  if (user1_ == NULL) {
    user1_ = new ::timeline::user;
  }
  // @@protoc_insertion_point(field_mutable:timeline.unfollow_request.user1)
  return user1_;
}
inline void unfollow_request::set_allocated_user1(::timeline::user* user1) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete user1_;
  }
  if (user1) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      user1 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, user1, submessage_arena);
    }
    
  } else {
    
  }
  user1_ = user1;
  // @@protoc_insertion_point(field_set_allocated:timeline.unfollow_request.user1)
}

// .timeline.user user2 = 2;
inline bool unfollow_request::has_user2() const {
  return this != internal_default_instance() && user2_ != NULL;
}
inline void unfollow_request::clear_user2() {
  if (GetArenaNoVirtual() == NULL && user2_ != NULL) {
    delete user2_;
  }
  user2_ = NULL;
}
inline const ::timeline::user& unfollow_request::user2() const {
  const ::timeline::user* p = user2_;
  // @@protoc_insertion_point(field_get:timeline.unfollow_request.user2)
  return p != NULL ? *p : *reinterpret_cast<const ::timeline::user*>(
      &::timeline::_user_default_instance_);
}
inline ::timeline::user* unfollow_request::release_user2() {
  // @@protoc_insertion_point(field_release:timeline.unfollow_request.user2)
  
  ::timeline::user* temp = user2_;
  user2_ = NULL;
  return temp;
}
inline ::timeline::user* unfollow_request::mutable_user2() {
  
  if (user2_ == NULL) {
    user2_ = new ::timeline::user;
  }
  // @@protoc_insertion_point(field_mutable:timeline.unfollow_request.user2)
  return user2_;
}
inline void unfollow_request::set_allocated_user2(::timeline::user* user2) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete user2_;
  }
  if (user2) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      user2 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, user2, submessage_arena);
    }
    
  } else {
    
  }
  user2_ = user2;
  // @@protoc_insertion_point(field_set_allocated:timeline.unfollow_request.user2)
}

// -------------------------------------------------------------------

// unfollow_response

// int32 success_status = 1;
inline void unfollow_response::clear_success_status() {
  success_status_ = 0;
}
inline ::google::protobuf::int32 unfollow_response::success_status() const {
  // @@protoc_insertion_point(field_get:timeline.unfollow_response.success_status)
  return success_status_;
}
inline void unfollow_response::set_success_status(::google::protobuf::int32 value) {
  
  success_status_ = value;
  // @@protoc_insertion_point(field_set:timeline.unfollow_response.success_status)
}

// -------------------------------------------------------------------

// list_request

// .timeline.user user1 = 1;
inline bool list_request::has_user1() const {
  return this != internal_default_instance() && user1_ != NULL;
}
inline void list_request::clear_user1() {
  if (GetArenaNoVirtual() == NULL && user1_ != NULL) {
    delete user1_;
  }
  user1_ = NULL;
}
inline const ::timeline::user& list_request::user1() const {
  const ::timeline::user* p = user1_;
  // @@protoc_insertion_point(field_get:timeline.list_request.user1)
  return p != NULL ? *p : *reinterpret_cast<const ::timeline::user*>(
      &::timeline::_user_default_instance_);
}
inline ::timeline::user* list_request::release_user1() {
  // @@protoc_insertion_point(field_release:timeline.list_request.user1)
  
  ::timeline::user* temp = user1_;
  user1_ = NULL;
  return temp;
}
inline ::timeline::user* list_request::mutable_user1() {
  
  if (user1_ == NULL) {
    user1_ = new ::timeline::user;
  }
  // @@protoc_insertion_point(field_mutable:timeline.list_request.user1)
  return user1_;
}
inline void list_request::set_allocated_user1(::timeline::user* user1) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete user1_;
  }
  if (user1) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      user1 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, user1, submessage_arena);
    }
    
  } else {
    
  }
  user1_ = user1;
  // @@protoc_insertion_point(field_set_allocated:timeline.list_request.user1)
}

// -------------------------------------------------------------------

// list_response

// string followers = 1;
inline void list_response::clear_followers() {
  followers_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& list_response::followers() const {
  // @@protoc_insertion_point(field_get:timeline.list_response.followers)
  return followers_.GetNoArena();
}
inline void list_response::set_followers(const ::std::string& value) {
  
  followers_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:timeline.list_response.followers)
}
#if LANG_CXX11
inline void list_response::set_followers(::std::string&& value) {
  
  followers_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:timeline.list_response.followers)
}
#endif
inline void list_response::set_followers(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  followers_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:timeline.list_response.followers)
}
inline void list_response::set_followers(const char* value, size_t size) {
  
  followers_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:timeline.list_response.followers)
}
inline ::std::string* list_response::mutable_followers() {
  
  // @@protoc_insertion_point(field_mutable:timeline.list_response.followers)
  return followers_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* list_response::release_followers() {
  // @@protoc_insertion_point(field_release:timeline.list_response.followers)
  
  return followers_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void list_response::set_allocated_followers(::std::string* followers) {
  if (followers != NULL) {
    
  } else {
    
  }
  followers_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), followers);
  // @@protoc_insertion_point(field_set_allocated:timeline.list_response.followers)
}

// string active_users = 2;
inline void list_response::clear_active_users() {
  active_users_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& list_response::active_users() const {
  // @@protoc_insertion_point(field_get:timeline.list_response.active_users)
  return active_users_.GetNoArena();
}
inline void list_response::set_active_users(const ::std::string& value) {
  
  active_users_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:timeline.list_response.active_users)
}
#if LANG_CXX11
inline void list_response::set_active_users(::std::string&& value) {
  
  active_users_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:timeline.list_response.active_users)
}
#endif
inline void list_response::set_active_users(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  active_users_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:timeline.list_response.active_users)
}
inline void list_response::set_active_users(const char* value, size_t size) {
  
  active_users_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:timeline.list_response.active_users)
}
inline ::std::string* list_response::mutable_active_users() {
  
  // @@protoc_insertion_point(field_mutable:timeline.list_response.active_users)
  return active_users_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* list_response::release_active_users() {
  // @@protoc_insertion_point(field_release:timeline.list_response.active_users)
  
  return active_users_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void list_response::set_allocated_active_users(::std::string* active_users) {
  if (active_users != NULL) {
    
  } else {
    
  }
  active_users_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), active_users);
  // @@protoc_insertion_point(field_set_allocated:timeline.list_response.active_users)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace timeline

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_timeline_2eproto__INCLUDED
